### PR TITLE
Remove contributors list from all pages

### PR DESCRIPTION
**Pull request by lifehackerhansol**
I can't tell if this works or not because it doesn't show at all with or without it within dev server lmfao

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Never mind it works. I am unsure how to make it show that way on Crowdin though, do I have to manually edit all of the themeConfigs?

**Comment by Epicpkmn11** [comment]
you need to upload the files to crowdin manually, I usually just run `crowdin push` with the CLI tool (requires being manager of the project, I can just update it)

**Comment by lifehackerhansol** [comment]
So I only need to edit the en_US stuff, then?

**Comment by Epicpkmn11** [comment]
yeah

**Comment by lifehackerhansol** [comment]
Then I think this PR is complete.

**Pull request merged**
