### PR TITLE
Add restoring a NAND backup page

### PR DESCRIPTION
**Pull request by Epicpkmn11**
Note: This is a draft since I need to
- [x] ~~Recommend a hex editor for linux, or at least remove that. For now it says TODO~~
- [x] ~~Do something about fwTool 1.6.0, whether link it or just tell people to find it~~
Neither are needed anymore
---
This adds a Restoring a NAND backup page, since while it is a dangerous thing to do its better to do it right than to struggle and mess up worse.

I have a preview of this (not technically this branch, I had to make some additional changes in `master` to get it working at this link) at https://pk11.us/dsi.cfw.guide/restoring-nand

Any feedback is appreciated, I will make this non-draft once I have sorted the issues mentioned above.

### CODE REVIEW

**Comment by NightYoshi370** [comment]
So what's the plan with this?

**Comment by Epicpkmn11** [comment]
Oh yeah, kinda forgot about this... Just read through it and it looks alright to me I think, just the two issues in the first post, and the hard mod section just says TODO right now...

For the linux hex editor we could prolly just remove that line, linux users can prolly look up hex editor on their own if their distro doesn't come with one
For hardmodding, maybe just link to https://web.archive.org/web/20151102221503/https://gbatemp.net/threads/dsi-downgrading-the-complete-guide.393682 for now?
For fwTool 1.6 I'm not really sure what's best...

**Comment by Epicpkmn11** [comment]
Updated TODO:
- [ ] Is there any way to get DSi BIOS files that work for no$gba without hardmodding? The ones dumped with fwTool are missing the RSA keys so they can't be used so you just have to *get* them at the moment
- [ ] Hard mod section is still todo
- [ ] Some parts could probably still do with tweaking, I made most of the warnings less harsh as flashing NAND is much less of a time bomb now (most flashes should be in the KBs, not ~250MB), but this is still very dangerous if you mess something up, especially if your uninstalling / don't have Unlaunch

Not directly this PR but related things:
- [ ] Since SafeNANDManger seems alright so far it'd probably be good to add a section for it to the uninstalling unlaunch page (with the installer method as a fallback if you don't have a NAND backup without unlaunch). This doesn't need to be in this PR, but should be done
- [ ] I really think SafeNANDManger needs more warnings, currently press <kbd>Y</kbd> and bam its flashing, at least it shouldn't do anything if nothing's changed, but that's still several minutes of it rechecking the whole NAND. I just don't feel comfortable recommending it without at least a warning screen and option to cancel after pressing <kbd>Y</kbd>. Maybe I'll PR this to it in a bit if that's alright.
- [ ] It'd be good to get more testing done with SafeNANDManager on hardware if people who can do hardmods are willing to test before recommending it for everyone to use, while it seems good so far, it hasn't been tested much. I installed TWiLight Menu++'s booter on one of my lesser-used DSi's and it went well, a few notes from my testing: 
   - I used ninfs to mount the NAND on macOS 10.14 and wrote TWiLight's booter's app and tmd
   - I did the flash first in no$gba and the DSI-1.MMC was identical to the nand.bin I flashed, so nothing got missed
   - It would probably not result in a brick if you installed homebrew without Unlaunch, testing with unpatched launcher and in no$gba with RSA enforced it would still boot to the launcher, however unless the launcher's RSA is patched you get "An error has occurred..." on launching the homebrew, so probably not a good idea
   - Visiting Data management in SysNAND settings (with Unlaunch installed) with TWiLight on SysNAND seemed fine
   - I didn't try uninstalling Unlaunch as I don't want to risk that on hardware, but in no$gba it seemed to work fine
   - No mismatch in FAT copies error when reinstalling Unlaunch

**Comment by urmum-69** [comment]
I think the nand dumper Arisotura provides for melonDS should be good
https://melonds.kuribo64.net/downloads/dsibiosdumper.7z

**Comment by Epicpkmn11** [comment]
Just tested, yep those dumps seem to work

**Comment by urmum-69** [comment]
I'll add instructions for using it then

**Comment by Epicpkmn11** [comment]
Is this done? Marked it ready for review as I think it is

**Comment by urmum-69** [comment]
the build of dsibiosdumper provided still hasn't been updated, so we can either just merge it and prompt arisotura or host it ourselves

**Comment by Epicpkmn11** [comment]
Ah yeah, honestly probably fine to just merge and maybe ping Arisotura about it again or something

**Pull request merged**
