### PR TITLE
treewide: update to VuePress 2.0.0-rc0, switch to emiyl's theme rewrite

### PR DESCRIPTION
**Pull request by lifehackerhansol**
- We can finally use Node 20
- Translations will be temporarily borked until Crowdin does its replication
- Move some configs around to align with new theme
- Searchbar is gone

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Drafting until the issue with ads is fixed

**Comment by emiyl** [comment]
why was 
```
		docsBranch: "master",
		docsDir: "docs",
```
removed?

all looks good to me aside from that

**Comment by lifehackerhansol** [comment]
I readded it anyway since it's useful otherwise.

**Comment by emiyl** [comment]
i'm also pretty sure that 

```
[ 'script', {}, 'if (localStorage.getItem("vuepress-color-scheme") === "dark" || (localStorage.getItem("vuepress-color-scheme") !== "light" && (window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches))) document.documentElement.classList.add("dark");' ]```

isn't needed anymore. unsure why it was there to begin with, probably some issue with a beta version

**Comment by emiyl** [comment]
also `docs/.vuepress/components` and `docs/.vuepress/styles` can be removed

**Comment by lifehackerhansol** [comment]
Ad issue fixed

need to fix sidebar, that died

**Comment by emiyl** [comment]
sidebar has issues in dev mode, seems to work fine on prod

**Review by NightScript370 — APPROVED** [review]
lgtm
Sidenote: I might work on making `docs/.vuepress/config.js` generate our locales rather than hardcoding every discord text, title, description, etc...

**Pull request merged**
